const express = require("express");
const router = express.Router();
const siteController = require("../app/controllers/SiteController");
const middlewareController = require("../app/controllers/MiddlewereController");
// console.log(newsController.index);
router.get("/login", siteController.login);
router.get("/register", siteController.register);
router.get("/show", siteController.getAllProduct);
router.post("/forgotpassword", siteController.forgotPassword);
router.get("/:slug", siteController.search);
module.exports = router;
